name: Test
on:
  push:
    branches:
      - '*'
      - '!main'
     
jobs:
  Trigger-Github-Scan:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Checkout THIS repository
        uses: actions/checkout@v2
     
      - name: Checkout OTHER repository
        uses: actions/checkout@v2
        with:
          repository: NHSDigital/software-engineering-quality-framework
          path: tmp
          ref: refs/heads/main

      - name: List files
        run: |
          ls -la tmp/tools/nhsd-git-secrets
          pwd


      - name: Preparing folder and file permissions
        run: |
          chmod 700 ./tmp/tools/nhsd-git-secrets/scan-repo-linux-mac.sh
          chmod 700 ./tmp/tools/nhsd-git-secrets/git-secrets
          cp ./tmp/tools/nhsd-git-secrets/git-secrets ${{ github.workspace }}
          ls -al ${{ github.workspace }}
         
      - name: Run Secret scan
        run: ./tmp/tools/nhsd-git-secrets/scan-repo-linux-mac.sh

  