name: Test
on:
  push:
    branches:
      - '*'
      - '!main'
     
jobs:
  Trigger-Github-Scan:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
     
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          respository: NHSDigital/software-engineering-quality-framework

      - name: List file
        run: |
          ls -la
          pwd
